analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_SCHEMA') }}"
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_PORT') }}"
      username: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: "{{ env_var('CLICKHOUSE_SECURE') }}"
      verify: "{{ env_var('CLICKHOUSE_VERIFY') }}"
      database: "{{ env_var('CLICKHOUSE_DB') }}"
      timeout: 300
